### ISSUE TITLE
Expiration of bearer tokens prevents leader board data from being retrieved

### ISSUE THREAD

**Issue by snowyPigeon** [Scottish-Tech-Army/ggs-frontend#10]
Leader board data does not retrieve unless the user regularly logs out and in.

This creates a need to create a new bearer token to enable the api request for leader board data.

Image from the Network tab in Firefox:

![image](https://user-images.githubusercontent.com/7503186/172214096-1816fb91-f649-4090-876d-d2b2041204e8.png)

**Comment by donal-s** [comment]
We're no longer using token based auth to identify team, so this problem should have gone away. Any objections to closing it?
